using Documenter
using CTBase
using Markdown
using MarkdownAST: MarkdownAST

# ═══════════════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════════════
draft = false # Draft mode: if true, @example blocks in markdown are not executed

# ═══════════════════════════════════════════════════════════════════════════════
# Docstrings from external packages
# ═══════════════════════════════════════════════════════════════════════════════
const DocumenterReference = Base.get_extension(CTBase, :DocumenterReference)

Modules = [Base]
for Module in Modules
    isnothing(DocMeta.getdocmeta(Module, :DocTestSetup)) &&
        DocMeta.setdocmeta!(Module, :DocTestSetup, :(using $Module); recursive=true)
end

# ═══════════════════════════════════════════════════════════════════════════════
# Repository configuration
# ═══════════════════════════════════════════════════════════════════════════════
repo_url = "github.com/control-toolbox/CTBase.jl"
src_dir = abspath(joinpath(@__DIR__, "..", "src"))
ext_dir = abspath(joinpath(@__DIR__, "..", "ext"))

# Helper to build absolute paths
src(files...) = [abspath(joinpath(src_dir, f)) for f in files]
ext(files...) = [abspath(joinpath(ext_dir, f)) for f in files]

# Symbols to exclude from documentation (auto-generated by @with_kw, etc.)
const EXCLUDE_SYMBOLS = Symbol[:include, :eval]

# ═══════════════════════════════════════════════════════════════════════════════
# Build documentation
# ═══════════════════════════════════════════════════════════════════════════════
makedocs(;
    draft=draft,
    remotes=nothing, # Disable remote links. Needed for DocumenterReference
    warnonly=true,
    sitename="CTBase.jl",
    format=Documenter.HTML(;
        repolink="https://" * repo_url,
        prettyurls=false,
        size_threshold_ignore=["api.md", "dev.md"],
        assets=[
            asset("https://control-toolbox.org/assets/css/documentation.css"),
            asset("https://control-toolbox.org/assets/js/documentation.js"),
        ],
    ),
    pages=[
        "Introduction" => "index.md",
        "API Reference" => [
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTBase => src("CTBase.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="CTBase",
                title_in_menu="CTBase",  # optionnel
                filename="ctbase",
            ),
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTBase => src("default.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Default",
                title_in_menu="Default",  # optionnel
                filename="default",
            ),
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTBase => src("description.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Description",
                title_in_menu="Description",  # optionnel
                filename="description",
            ),
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTBase => src("exception.jl")],
                external_modules_to_document=[Base],  # pour inclure Base.showerror
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Exception",
                title_in_menu="Exception",  # optionnel
                filename="exception",
            ),
            CTBase.automatic_reference_documentation(;
                subdirectory=".",
                primary_modules=[CTBase => src("utils.jl")],
                exclude=EXCLUDE_SYMBOLS,
                public=false,
                private=true,
                title="Utils",
                title_in_menu="Utils",  # optionnel
                filename="utils",
            ),
        ],
    ],
    checkdocs=:none,
)

# ═══════════════════════════════════════════════════════════════════════════════
# Deploy documentation to GitHub Pages
# ═══════════════════════════════════════════════════════════════════════════════
deploydocs(; repo=repo_url * ".git", devbranch="main")
