# Ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests
name: Breakage

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  break:
    strategy:
      fail-fast: false
      matrix:
        pkg: ["control-toolbox/CTDirect.jl", "control-toolbox/CTFlows.jl", "control-toolbox/OptimalControl.jl"]
        pkgversion: [latest, stable]
    uses: control-toolbox/CTActions/.github/workflows/breakage.yml@main
    with:
      pkg: ${{ matrix.pkg }}
      pkgversion: ${{ matrix.pkgversion }}
