# Ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests
name: Breakage

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  call:
    if: contains(github.event.pull_request.labels.*.name, 'run breakage')
    strategy:
      fail-fast: false
      matrix:
        pkgname: [CTDirect, CTFlows, CTModels, CTParser, OptimalControl]
        pkgversion: [latest, stable]
        include:
          - pkgpath: control-toolbox
    uses: control-toolbox/CTActions/.github/workflows/breakage.yml@main
    with:
      pkgname: ${{ matrix.pkgname }}
      pkgpath: ${{ matrix.pkgpath }}
      pkgversion: ${{ matrix.pkgversion }}
