name: Update README with ABOUT.md and INSTALL.md

on:
  schedule:
    - cron: '0 6 * * 1'   # every Monday at 06:00 UTC
  workflow_dispatch:       # manual trigger

jobs:
  call-shared:
    uses: control-toolbox/CTActions/.github/workflows/update-readme.yml@main
    with:
      template_file: README.template.md
      output_file: README.md
      package_name: CTBase   # package for INSTALL.md
      repo_name: CTBase.jl   # repository for CONTRIBUTING.md links
    secrets: inherit
